collections:
  ctf:
    output: true
    permalink: /ctf/:title/
  wireshark:
    output: true
    permalink: /wireshark/:title/
  treathunting:
    output: true
    permalink: /threathunting/:title/
  malware:
    output: true
    permalink: /malware/:title/
  tools:
    output: true
    permalink: /tools/:title/
  glossary:
    output: true
    permalink: /glossary/:title/

defaults:
  - scope:
      path: ""
      type: ctf
    values:
      layout: collection
  - scope:
      path: ""
      type: wireshark
    values:
      layout: collection
  - scope:
      path: ""
      type: treathunting
    values:
      layout: collection
  - scope:
      path: ""
      type: malware
    values:
      layout: collection
  - scope:
      path: ""
      type: tools
    values:
      layout: collection
  - scope:
      path: ""
      type: glossary
    values:
      layout: glossary

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # add other plugins as needed
